version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react*"
        update-types:
          - "major"
      - dependency-name: "react-router-dom"
        update-types:
          - "major"
    reviewers:
      - "Dakster-z"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"